name: "Archive and Slack: DailyMail.co.uk"

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  archive-site:
    name: "Archive bundle"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Archive DailyMailUK
        uses: turbodatadrifter3tdi/news-homepages/.github/workflows/archive-DailyMailUk.yml@si-branch
        with:
          handle: DailyMailUK
        secrets: inherit

  newsroom-slack:
    name: "Post to newsroom Slack"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [archive-site]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Post to Slack
        uses: ./.github/actions/slack
        with:
          handle: DailyMailUK
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL_YOUR_SITE_HANDLE_IN_CAPS }}
